# Generated by Django 2.0 on 2017-12-28 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date', models.DateTimeField(verbose_name='examination date')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='marks_system.Examination')),
                ('students', models.ManyToManyField(to='marks_system.Student')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks_system.Examination'),
        ),
        migrations.AddField(
            model_name='mark',
            name='students',
            field=models.ManyToManyField(to='marks_system.Student'),
        ),
    ]
