#!/usr/bin/env python
# -*-coding:Utf-8 -*

EXPEDITEUR='HERE_YOUR_ADDRESS@gmail.com'
DESTINATAIRE='HERE_YOUR_ADDRESS@gmail.com'
MY_PASSWORD='****PASS****'

MAIL_SEND_ERROR="MAIL SENDING ERROR"
MAIL_AUTHENTIFICATION_ERROR="AUTHENTIFICATION ERROR"